server.port: 8083

spring:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/albums?useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    tomcat:
      max-active: 4
      max-idle: 4
      min-idle: 4
      initial-size: 4

logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG

s3:
  accessKey: <access key id>
  secretKey: <secret access key>
  bucketName: <name of the bucket>
